// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjo1uRR5iSphmp2thDtUJeBRfSxzc_5PE',
    appId: '1:1095280799890:web:fe54fc775db754f703364b',
    messagingSenderId: '1095280799890',
    projectId: 'flutter-auth-prj',
    authDomain: 'flutter-auth-prj.firebaseapp.com',
    storageBucket: 'flutter-auth-prj.appspot.com',
    measurementId: 'G-RSLWGRKKQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMVJI1hq6j734KvqwXjI9VZNzB12b7MMA',
    appId: '1:1095280799890:android:c494ed479c6f493303364b',
    messagingSenderId: '1095280799890',
    projectId: 'flutter-auth-prj',
    storageBucket: 'flutter-auth-prj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwRlQxgYxEZJ24E_kzEkVvDWCNzVJsqBc',
    appId: '1:1095280799890:ios:c04b5956b0689c5003364b',
    messagingSenderId: '1095280799890',
    projectId: 'flutter-auth-prj',
    storageBucket: 'flutter-auth-prj.appspot.com',
    iosClientId: '1095280799890-v5oqgkfsk0n530p1o23i1ri74dk1t2ch.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwRlQxgYxEZJ24E_kzEkVvDWCNzVJsqBc',
    appId: '1:1095280799890:ios:c04b5956b0689c5003364b',
    messagingSenderId: '1095280799890',
    projectId: 'flutter-auth-prj',
    storageBucket: 'flutter-auth-prj.appspot.com',
    iosClientId: '1095280799890-v5oqgkfsk0n530p1o23i1ri74dk1t2ch.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireapp',
  );
}
